### PR TITLE
feat: Add new validators

### PR DESCRIPTION
**Pull request by RyanFelt**

### CODE REVIEW

**Comment by RyanFelt** [comment]
Updated some previous values names/descriptions, does this get completely updated every time or it checks only for new entries?

Also you need to increase the scriptHash length as they can have stakeKeys or maybe I am missing something?

**Comment by ashisherc** [comment]
@RyanFelt if the stake key is a contract, you can add it separately as a new entry under contracts. It is not required to attach stakekey to the contract (note this is not an address, but a contract hash)

Also, please reduce the name length to 45 char, longer names wont be visible properly in UI hence we are enforcing the name length limit. Its more like a label. You can use the description field to add a lengthy description. 

Also please see this to validate your changes locally, https://github.com/StricaHQ/cardano-contracts-registry#5-validate-your-changes

**Comment by RyanFelt** [comment]
The stakeKey is not a contract but our validator includes a stakeKey, here is the example of one of them: https://cardanoscan.io/address/addr1z9es6px68rlmwatqwg6qxwqf3szyz0n4lm0m2e5j38nu0062a6yhtrq8a4cxg2trrtzddev7v974nafzmx4xaegv2ngqky7khv

Here you can see it being used in a tx: https://cardanoscan.io/transaction/939d4929a58c2e5a80606e32ef243f5e58f1c0867f5a46b75af6c6f152aedf04?tab=contracts

**Comment by ashisherc** [comment]
right, which is okay. you only have to register the contract hash which is 28 byte hash (56 chars hex string), in your case its the payment key of your address

**Comment by RyanFelt** [comment]
Oh I see you will handle that in the backend. For addresses with a stakeKey isn't the hex of the paymentKey 58 instead of 56?

**Comment by ashisherc** [comment]
hash is always 28 bytes, first 1 bytes represents the header of an address. note we only need to register the hash and not an address.

**Comment by RyanFelt** [comment]
So in the case of this validator: https://cardanoscan.io/address/addr1z9es6px68rlmwatqwg6qxwqf3szyz0n4lm0m2e5j38nu0062a6yhtrq8a4cxg2trrtzddev7v974nafzmx4xaegv2ngqky7khv

I would assume you are looking for:
730d04da38ffb7756072340338098c04413e75fedfb5669289e7c7bf4a

What am I missing?

**Comment by ashisherc** [comment]
last 2 chars "4a" are part of your stake key

**Comment by RyanFelt** [comment]
Okay I see, I was using cardanoscan to validate my values and it confused me. Thanks for the info!

**Comment by ashisherc** [comment]
I too used Cardanoscan to validate your info, you might also want to take a look at https://cardanoscan.io/addressInspector, if you want to verify your addresses

**Comment by RyanFelt** [comment]
This is a useful tool for on the go, thanks

**Comment by RyanFelt** [comment]
As for the name length, everything has been standardize so to change any data will make it not very useful as we describing it with as little data as possible, would the values get cut off or you will just not except it at all?

**Comment by ashisherc** [comment]
its just that the values will be truncated in the UI, I can merge it if you wish to. But as I said, there is a description field for this.

**Comment by RyanFelt** [comment]
Yeah thats okay with us, thanks again!

**Pull request merged**
