### PR TITLE
feat: Add current VyFi vault validators

### PR DESCRIPTION
**Pull request by RyanFelt**

### CODE REVIEW

**Comment by RyanFelt** [comment]
Let me update our scriptHash as it has the prepend "71". In regards to our twitter url and validator names could you expend the character length? That is the current naming convention we are using on your app.

**Comment by ashisherc** [comment]
@RyanFelt thanks for the PR

1. Twitter, please use only the username without `@`
2. We are restricting the contract name length to be compact because it is shown in place of the address, if the length is too big, it will be trimmed and hence will not look good. Also, note that the `labelPrefix + contract.name` will form the actual label. Hence can you re-do the contract name to be compact?

**Comment by RyanFelt** [comment]
Np, let me update the twitter info.

You guys can choose to do whatever you want and I am not trying to argue but most addresses will either have a length of about 58 or 103. That is much longer than what you are limiting, we currently have labels that have the same lengths that we are requesting and they work fine with no trimming. Here is an example: https://cardanoscan.io/address/addr1wxtv54zpvmntf6czfwttjyzy08wg47d3xm580uqsacklalgydvl3q

If we need to trim it down we will not have the info needed and at that point the label is kind of pointless

**Comment by ashisherc** [comment]
your inputs are very much welcome, we always want to work with the community. The truncating I mentioned is used in lists where many transactions are displayed. And the current length of such a viewing element is 30 chars, see https://cardanoscan.io/transactions. Though I also believe that labels being truncated for such lists isn't a big issue. So we can have big enough labels as you are suggesting. 

Also, labels as big as 58+ chars are not a good user experience, the contract description field can be used for much more detailed info or message (which will be displayed soon on the explorer)

Let's have a label length limit of 45 chars (which will suffice your need), and we can increase it as per more dApps requirements.

**Pull request merged**
