### PR TITLE
Adding tokenriot info

### PR DESCRIPTION
**Pull request by logicalmechanism**
Adding the mainnet contract information for Token Riot. The JSON validates with `npm run validate`.

### CODE REVIEW

**Comment by ashisherc** [comment]
@logicalmechanism 

plz do not include package-lock and yarn lock changes

**Comment by logicalmechanism** [comment]
> @logicalmechanism
> 
> plz do not include package-lock and yarn lock changes

I will remove them and push the changes right now.

**Comment by ashisherc** [comment]
I meant you must not edit them (also not delete them from the code). leave them as is. You will need to force push the commits after reverting your changes locally

**Comment by logicalmechanism** [comment]
> I meant you must not edit them (also not delete them from the code). leave them as is. You will need to force push the commits after reverting your changes locally

OK, only file to change is my addition now.

**Comment by logicalmechanism** [comment]
@ashisherc Is the PR good now or do I need to change anything else?

**Pull request merged**
