### PR TITLE
please add pfpmoji.json metadata to cardanoscan.io

### PR DESCRIPTION
**Pull request by havealoha**
please add pfpmoji.json metadata to cardanoscan.io

### CODE REVIEW

**Comment by ashisherc** [comment]
@havealoha please add at least one contract, see here https://github.com/StricaHQ/cardano-contracts-registry#4-add-contracts-details

**Comment by havealoha** [comment]
Is this better @ashisherc  https://github.com/havealoha/cardano-contracts-registry/commit/f3fd81fd370cc441fc88959f8b0fa7085a221769

**Comment by ashisherc** [comment]
@havealoha please re-verify the format.  https://github.com/StricaHQ/cardano-contracts-registry#4-add-contracts-details

**Comment by havealoha** [comment]
I think I got it?

https://github.com/havealoha/cardano-contracts-registry/commit/50f7f3606a57328460fda7764fd7885f0ef1af32

**Comment by ashisherc** [comment]
@havealoha also plz change as per below, 

- "contract" to "contracts"
- contracts is an array, with your script as one item

**Comment by ashisherc** [comment]
@havealoha please convert it to an array, see item 2 in my previous comment

**Comment by havealoha** [comment]
Phew, https://github.com/havealoha/cardano-contracts-registry/commit/f50ec305c6bd09642c3e2b2ad1606606799cb762

**Comment by ashisherc** [comment]
@havealoha "languageVersion" is required, the value would be 1 for your. This should be the last change. BTW you could also validate this locally before the see, PR https://github.com/StricaHQ/cardano-contracts-registry#5-validate-your-changes

**Comment by ashisherc** [comment]
@havealoha done

**Comment by havealoha** [comment]
I think if the project description will not be shown on the explorer, and
the policy description is shown instead, maybe I'll copy the description
from the project to the policy.

Is the layout of the info displayed in the explorer set in stone? Thoughts
about displaying description?

**Comment by ashisherc** [comment]
@havealoha you can add the description to the policy, and it will update on the explorer after merge.

**Pull request merged**
